### PR TITLE
1.12

### PR DESCRIPTION
**Pull request by SpGilbert**
Are there any other files I need to edit for this pull request to add the other two types of stone from quark to be added to the base mod?

### CODE REVIEW

**Comment by PersonTheCat** [comment]
Hey, thank you so much for your contribution! It's almost all. BlockInit is missing the check for `quarkJasperOn` and then the two entries need to be added to `BlockGroup#DEFAULT_GROUP_INFO` so they can show up by default. That was kept in a super bizarre location, though, I know. The mod definitely needed to be restructured a bit and that's what I'm working on now with the rewrite for 1.14. 

Anyway, I'll fix those two things when I get a minute later today and upload to CurseForge. Thanks again for your contribution!

**Comment by SpGilbert** [comment]
Do you need me to finish any other files for that since I only now have my pc up since I was doing a data transfer

**Comment by PersonTheCat** [comment]
It should be good, actually, but thank you!

**Comment by SpGilbert** [comment]
Well I hope you remember to upload it to curseforge

**Comment by PersonTheCat** [comment]
Looks like it's still under review, for some reason. Hopefully it'll get approved by tomorrow.

**Comment by SpGilbert** [comment]
ok

**Comment by SpGilbert** [comment]
and it seems they have not approved it

**Comment by PersonTheCat** [comment]
It seems fine to me. Here's the link I have. https://www.curseforge.com/minecraft/mc-mods/ore-stone-variants/files/2780602

**Comment by SpGilbert** [comment]
oh didn't see it must have missed it

**Pull request closed without merging**
