### PR TITLE
Fixes for current 1.16.3 Forge

### PR DESCRIPTION
**Pull request by clockler**

### CODE REVIEW

**Comment by PersonTheCat** [comment]
It's been a long time since I got one of these on a personal project. I really, really appreciate your help! I'm working from home today, so hopefully I can review this in a bit.

**Comment by clockler** [comment]
I should have noted: this has a regression in that in-config loot tables don't work anymore with these changes, as I wasn't able to find an easy way to fit them in with transitioning the config loot table definition to use a `ResourceLocation` to be parsed later. They can still be declared in a custom datapack with OpenLoader or similar, or they could be loaded in a `FMLCommonSetupEvent` handler as I was doing before? They just need to be parsed as loot tables *after* the `RegistryEvent`s are fired.

**Comment by PersonTheCat** [comment]
I can merge the changes from [4b92ce6](https://github.com/PersonTheCat/ore_stone_variants/pull/105/commits/4b92ce617f8cac0f0670ff584870352269186245) and [2e7980c](https://github.com/PersonTheCat/ore_stone_variants/pull/105/commits/2e7980c48df7f23c51f37148cefb7306c311cf85), but I'm not sure I understand what's going on with the loot table changes. This field is supposed to be optional and is only needed when the user wants to explicitly define the loot table from within the preset. Otherwise, it should just get the drops directly from `ore` and thus these changes aren't needed. Could you elaborate on that?

**Comment by PersonTheCat** [comment]
I believe everything but the loot changes have been implemented in the main branch. Gonna have to reject. Feel free to reopen this and we can continue discussion. Thanks again for your help!

**Pull request closed without merging**
